/** @type {import('tailwindcss').Config} */
module.exports = {
  content: [
    './*.php',
    './config/**/*.php',
    './core/**/*.php',
    './includes/**/*.php',
    './lib/**/*.php',
    './modules/**/*.php',
    './public/**/*.php',
    './public/**/*.html',
    './public/assets/**/*.js',
    './resources/**/*.php',
    './resources/**/*.html',
    './resources/**/*.js',
    './manuales_web/**/*.php',
    './manuales_web/**/*.html',
    './sql/**/*.php',
  ],
  theme: {
    extend: {
      colors: {
        primary: {
          50: '#e6edf5',
          100: '#b3c9e0',
          200: '#80a5cb',
          300: '#4d81b6',
          400: '#2663a0',
          500: '#1a365d',
          600: '#152b4a',
          700: '#0f2037',
          800: '#0a1628',
          900: '#050d14',
        },
        accent: '#48bb78',
        accentDark: '#38a169',
        'panel-blue': '#3b82f6',
        'panel-purple': '#8b5cf6',
        'panel-green': '#10b981',
        'panel-amber': '#f59e0b',
        'panel-cyan': '#06b6d4',
        'panel-red': '#ef4444',
        'panel-indigo': '#6366f1',
        'panel-dark': '#111827',
      },
      fontFamily: {
        sans: ['Inter', 'system-ui', 'sans-serif'],
        display: ['Montserrat', 'Inter', 'system-ui', 'sans-serif'],
      },
    },
  },
  plugins: [],
};
