name: Despliegue de PRUEBAS (BETA)
on:
  push:
    branches:
      - develop # Se activa solo cuando trabajas en esta rama

jobs:
  FTP-Deploy-Action:
    name: FTP-Deploy-Action
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0

    - name: 🚀 Subiendo a carpeta BETA
      uses: SamKirkland/FTP-Deploy-Action@v4.3.5
      with:
        server: ${{ secrets.FTP_SERVER }}
        username: ${{ secrets.FTP_USERNAME }}
        password: ${{ secrets.FTP_PASSWORD }}
        # NOTA: Asegúrate de que esta carpeta exista en tu cPanel
        server-dir: public_html/mistorneos_beta/
        security: loose
        dangerous-clean-slate: false
        exclude: |
          **/.git*
          **/.github*
          **/node_modules/**
          .env
          **/upload/**
          **/uploads/**