name: Despliegue Automatico
on:
  push:
    branches:
      - main
jobs:
  FTP-Deploy-Action:
    name: FTP-Deploy-Action
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0

    - name: 🚀 Subiendo archivos
      uses: SamKirkland/FTP-Deploy-Action@v4.3.5
      with:
        server: ${{ secrets.FTP_SERVER }}
        username: ${{ secrets.FTP_USERNAME }}
        password: ${{ secrets.FTP_PASSWORD }}
        server-dir: public_html/mistorneos_fvd/
        # Mantenemos esto para evitar errores de certificado en cPanel
        security: loose
        # No borramos nada que ya exista y no esté en GitHub
        dangerous-clean-slate: false
        exclude: |
          **/.git*
          **/.github*
          **/node_modules/**
          .env
          **/upload/**
          **/uploads/**
          **/.vscode/**